### ISSUE TITLE
数据来源

### ISSUE THREAD

**Issue by jiangxiaolin** [bluemapleman/NewsRecommendSystem#1]
你好，想问下数据来源，newslogs这个表的数据怎么获取的，我看到的TestDataProcessor只是爬取网易的新闻，并没有某个用户的历史记录.

**Comment by bluemapleman** [comment]
你好，


  newslogs表的数据入库在设定中应该是程序本身的逻辑，即每当有用户点击一个新闻，就会在数据库中插入一条新的浏览记录。


  而提供的测试数据是为了出测试效果而人为构造的记录。

 原始邮件
发件人: 江小林<notifications@github.com>
收件人: bluemapleman/NewsRecommendSystem<NewsRecommendSystem@noreply.github.com>
抄送: Subscribed<subscribed@noreply.github.com>
发送时间: 2018年1月12日(周五) 18:25
主题: [bluemapleman/NewsRecommendSystem] 数据来源 (#1)


你好，想问下数据来源，newslogs这个表的数据怎么获取的，我看到的TestDataProcessor只是爬取网易的新闻，并没有某个用户的历史记录.

**Comment by jiangxiaolin** [comment]
“每当有用户点击一个新闻”  指的是网易的浏览用户呢 还是 程序里的呢  没看到有这个逻辑  能说下在哪吗？我看程序里是直接根据数据库的结果进行三种方式的推荐

**Comment by bluemapleman** [comment]
是这样的：这个推荐系统原本是应该是工作在一个新闻门户的底层的，比如说加入我这个操作系统是作为网易新闻的推荐系统在运行的，那么浏览记录应该就是每一次任何一个正在看网易新闻网页的用户，当它每点击一个新闻，那么它的用户id+新闻id+浏览时间就会作为一条浏览记录插入到newslogs表中。而这个逻辑应该是网页端和后台实现的，推荐系统只负责用数据表存储浏览记录。


一言以蔽之，这个推荐系统需要配合已有的用户看新闻的接口实现（可以是类似网易新闻的浏览器页面，可以是类似今日头条的app界面）运行，而“每当有用户点击一个新闻”指的就是每当你的用户通过新闻接口访问/浏览了某条新闻，你的接口需要自己写一个逻辑，在用户出现浏览行为时，把相应浏览记录的插入到推荐系统的newslogs表中。

 原始邮件
发件人: 江小林<notifications@github.com>
收件人: bluemapleman/NewsRecommendSystem<NewsRecommendSystem@noreply.github.com>
抄送: Tom Qian<TomQianMaple@Outlook.com>; Comment<comment@noreply.github.com>
发送时间: 2018年1月15日(周一) 09:46
主题: Re: [bluemapleman/NewsRecommendSystem] 数据来源 (#1)


“每当有用户点击一个新闻” 指的是网易的浏览用户呢 还是 程序里的呢 没看到有这个逻辑 能说下在哪吗？我看程序里是直接根据数据库的结果进行三种方式的推荐

**Comment by jiangxiaolin** [comment]
OK  清楚了  非常感谢
