### ISSUE TITLE
导入项目错误

### ISSUE THREAD

**Issue by YO7LK** [bluemapleman/NewsRecommendSystem#12]
提示Build Path错误，还有Maven Dependency错误。和我jdk装的1.8.0_201是否有关呢？之前没用过maven需要配置哪些呢？
![TIM图片20190409101224](https://user-images.githubusercontent.com/28487842/55768708-83978500-5ab0-11e9-9840-65dcaa4fcafa.jpg)
![屏幕截图(40)](https://user-images.githubusercontent.com/28487842/55768716-88f4cf80-5ab0-11e9-876d-2c99596df515.png)

**Comment by bluemapleman** [comment]
感谢提出问题！

我重新导入了了一遍看了下，确实有一个源文件夹丢失的报错问题，我已经把那个不存在的源文件架索引删除了，现在项目应该没有问题了。

- 项目导入方面

如果是eclipse，import->import->maven->existing maven project

- Maven方面

如果之前没有安装1.本地maven以及2.eclipse对应的maven插件的话，可以参考这篇教程https://www.cnblogs.com/little-YTMM/p/5970878.html，先安装好相应的工具，然后再按上述流程导入项目。

如果还有问题，欢迎跟进！

**Comment by YO7LK** [comment]
Thanks！
